In [ ]:
import pandas as pd # for data manipulation
import numpy as np # for numerical operations
from scipy.stats import chi2_contingency # Direct import for Chi-Square test

data=pd.read_csv('/content/world all university rank and rank score.csv')
#view the first few rows of dataset
data.head()

#Create a contingency table
contingency_table = pd.crosstab(data['location'], data['rank'])

# Perform the Chi-Square test
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Output results
print("Chi-Square Statistic:", chi2)
print("P-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

# Interpretation
alpha = 0.05
if p < alpha:
    print("Reject the null hypothesis: The variables are dependent.")
else:
    print("Fail to reject the null hypothesis: The variables are independent.")


Chi-Square Statistic: 67567.86437027025
P-value: 0.10488369324773616
Degrees of Freedom: 67108
Expected Frequencies:
 [[0.03786192 0.03786192 0.03786192 ... 0.03786192 0.03786192 0.03786192]
 [0.00556793 0.00556793 0.00556793 ... 0.00556793 0.00556793 0.00556793]
 [0.00222717 0.00222717 0.00222717 ... 0.00222717 0.00222717 0.00222717]
 ...
 [0.09131403 0.09131403 0.09131403 ... 0.09131403 0.09131403 0.09131403]
 [0.15924276 0.15924276 0.15924276 ... 0.15924276 0.15924276 0.15924276]
 [0.00445434 0.00445434 0.00445434 ... 0.00445434 0.00445434 0.00445434]]
Fail to reject the null hypothesis: The variables are independent.


In [ ]:
import pandas as pd
# Sample data: Water usage survey by college students
data = {
    "Student ID": ["STU001", "STU002", "STU003", "STU004", "STU005"],
    "Drinking (L/day)": [2.5, 3.0, 2.0, 1.8, 2.2],
    "Washing (L/day)": [10, 15, 8, 12, 18],
    "Bathing (L/day)": [50, 60, 45, 55, 70],
    "Other (L/day)": [5, 8, 4, 6, 10]
}

# Recommended limits (example values in liters per day)
recommended_limits = {
    "Drinking (L/day)": 3.0,
    "Washing (L/day)": 12,
    "Bathing (L/day)": 50,
    "Other (L/day)": 6
}

# Convert data to a DataFrame
df = pd.DataFrame(data)

# Evaluate water usage
def evaluate_usage(row):
    issues = []
    for activity, limit in recommended_limits.items():
        if row[activity] > limit:
            issues.append(f"{activity} exceeds limit")
    return ", ".join(issues) if issues else "Usage within limits"

# Apply evaluation
df["Usage Status"] = df.apply(evaluate_usage, axis=1)

# Calculate total water usage per student
df["Total Usage (L/day)"] = df[
    ["Drinking (L/day)", "Washing (L/day)", "Bathing (L/day)", "Other (L/day)"]
].sum(axis=1)

# Display the results
print("Water Usage Analysis Report")
print(df)

# Summary statistics for total usage
print("\nSummary Statistics:")
print(df["Total Usage (L/day)"].describe())

# Identify students exceeding 100 liters/day
print("\nStudents Exceeding 100 Liters/Day:")
print(df[df["Total Usage (L/day)"] > 100])


Water Usage Analysis Report
  Student ID  Drinking (L/day)  Washing (L/day)  Bathing (L/day)  \
0     STU001               2.5               10               50   
1     STU002               3.0               15               60   
2     STU003               2.0                8               45   
3     STU004               1.8               12               55   
4     STU005               2.2               18               70   

   Other (L/day)                                       Usage Status  \
0              5                                Usage within limits   
1              8  Washing (L/day) exceeds limit, Bathing (L/day)...   
2              4                                Usage within limits   
3              6                      Bathing (L/day) exceeds limit   
4             10  Washing (L/day) exceeds limit, Bathing (L/day)...   

   Total Usage (L/day)  
0                 67.5  
1                 86.0  
2                 59.0  
3                 74.8  
4          

ANOVA Test
ANOVA (Analysis of Variance) is a statistical method used to compare the means of three or more groups to see if there are significant differences between them. We’ll analyze whether students’ scores in three different subjects (e.g., Math, Science, and English) have significantly different means.
ANOVA Analysis for College Students


In [ ]:
import pandas as pd
import scipy.stats as stats # for statistical functions
# Sample data: Scores of students in different subjects
data = {
    "Math": [85, 90, 88, 92, 75, 80, 95, 85, 89, 91],
    "Science": [88, 86, 89, 91, 78, 84, 90, 87, 85, 88],
    "English": [82, 80, 85, 83, 79, 81, 84, 83, 86, 87]
}

# Convert data to a DataFrame
df = pd.DataFrame(data)

# Perform ANOVA test
f_stat, p_value = stats.f_oneway(df["Math"], df["Science"], df["English"])

# Display the results
print("ANOVA Results:")
print(f"F-Statistic: {f_stat:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpret the results
alpha = 0.05  # Significance level
if p_value < alpha:
    print("\nConclusion: There is a significant difference between the means of the groups.")
else:
    print("\nConclusion: There is no significant difference between the means of the groups.")


ANOVA Results:
F-Statistic: 2.60
P-Value: 0.0929

Conclusion: There is no significant difference between the means of the groups.
